name: C++ Build Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Compile all .cpp files
      run: |
        set -e
        for file in $(find . -name "*.cpp"); do
          echo "Compiling $file..."
          g++ -std=c++17 -Wall -Werror -o /tmp/out "$file"
        done
